// app/(admin)/_constants_/data/countries.ts

export const countries = [
  { code: 'TR', name: 'Türkiye' },
  { code: 'US', name: 'Amerika Birleşik Devletleri' },
  { code: 'UK', name: 'İngiltere' },
  { code: 'DE', name: 'Almanya' },
  { code: 'FR', name: 'Fransa' },
  { code: 'CA', name: 'Kanada' },
  { code: 'IT', name: 'İtalya' },
  { code: 'ES', name: 'İspanya' },
  { code: 'CN', name: 'Çin' },
  { code: 'JP', name: 'Japonya' },
  { code: 'KR', name: 'Güney Kore' },
  { code: 'IN', name: 'Hindistan' },
  { code: 'RU', name: 'Rusya' },
  { code: 'BR', name: 'Brezilya' },
  { code: 'MX', name: 'Meksika' },
  { code: 'AU', name: 'Avustralya' },
  { code: 'NL', name: 'Hollanda' },
  { code: 'CH', name: 'İsviçre' },
  { code: 'SE', name: 'İsveç' },
  { code: 'NO', name: 'Norveç' },
  { code: 'DK', name: 'Danimarka' },
  { code: 'FI', name: 'Finlandiya' },
  { code: 'BE', name: 'Belçika' },
  { code: 'AT', name: 'Avusturya' },
  { code: 'PL', name: 'Polonya' },
  { code: 'CZ', name: 'Çekya' },
  { code: 'GR', name: 'Yunanistan' },
  { code: 'PT', name: 'Portekiz' },
  { code: 'HU', name: 'Macaristan' },
  { code: 'IE', name: 'İrlanda' },
  { code: 'NZ', name: 'Yeni Zelanda' },
  { code: 'AR', name: 'Arjantin' },
  { code: 'CL', name: 'Şili' },
  { code: 'ZA', name: 'Güney Afrika' },
  { code: 'EG', name: 'Mısır' },
  { code: 'IL', name: 'İsrail' },
  { code: 'AE', name: 'Birleşik Arap Emirlikleri' },
  { code: 'SA', name: 'Suudi Arabistan' },
  { code: 'SG', name: 'Singapur' },
  { code: 'TH', name: 'Tayland' },
  { code: 'MY', name: 'Malezya' },
  { code: 'ID', name: 'Endonezya' },
  { code: 'PH', name: 'Filipinler' },
  { code: 'VN', name: 'Vietnam' },
  { code: 'UA', name: 'Ukrayna' },
  { code: 'RO', name: 'Romanya' },
  { code: 'BG', name: 'Bulgaristan' },
  { code: 'PK', name: 'Pakistan' },
  { code: 'BD', name: 'Bangladeş' },
];

