// // src/features/products/data.ts
// import type { Product } from "./types";

// export const CATEGORY_TREE: Record<string, string[]> = {
//   Profil:   ['Kasa', 'Kanat', 'Kilit', 'Fitil Kanalı'],
//   Kapı:     ['Sürme', 'Menteşe', 'Ray'],
//   Pencere:  ['Çift Açılım', 'Sürme', 'Aksesuar'],
//   Aksesuar: ['Vida', 'Köşe', 'Fitil'],
// };

// export const ALL_CATEGORIES = Object.keys(CATEGORY_TREE);
// export const ALL_VARIANTS   = ['Kasa', 'Kanat', 'Ray', 'Fitil', 'Kilit'];

// export const MOCK_PRODUCTS: Product[] = [
//   {
//     id: '1',
//     code: 'T2513',
//     name: 'Alüminyum Kasa 60',
//     variant: 'Kasa',
//     unitWeightKg: 1.25,
//     category: 'Profil',
//     subCategory: 'Kasa',
//     date: '2025-08-10',
//     image: 'https://placehold.co/600x400?text=T2513',
//     drawer: 'Mehmet Yılmaz',
//     control: 'Ayşe Demir',
//     scale: '1.5 / 1',
//     outerSizeMm: 120,
//     sectionMm2: 450,
//     unitWeightGrPerM: 1250,
//     displayName: 'Alüminyum Kasa 60 mm',
//     tempCode: 'GC-101',
//     profileCode: 'T-2513',
//     manufacturerCode: 'Ü-90001',
//   },
//   {
//     id: '2',
//     code: 'T2515',
//     name: 'Kanat Profili Pro',
//     variant: 'Kanat',
//     unitWeightKg: 0.88,
//     category: 'Profil',
//     subCategory: 'Kanat',
//     date: '2025-07-22',
//     image: 'https://placehold.co/600x400?text=T2515',
//     drawer: 'Ali Kaya',
//     control: 'Zeynep K.',
//     scale: '1 / 1',
//     outerSizeMm: 95,
//     sectionMm2: 310,
//     unitWeightGrPerM: 880,
//     displayName: 'Kanat Profili Profesyonel',
//     tempCode: 'GC-234',
//     profileCode: 'T-2515',
//     manufacturerCode: 'Ü-91234',
//   },
//   {
//     id: '3',
//     code: 'T2510',
//     name: 'Sürme Rayı 40',
//     variant: 'Ray',
//     unitWeightKg: 1.05,
//     category: 'Kapı',
//     subCategory: 'Ray',
//     date: '2025-06-15',
//     image: 'https://placehold.co/600x400?text=T2510',
//     drawer: 'Cem Arslan',
//     control: 'Elif T.',
//     scale: '2 / 1',
//     outerSizeMm: 140,
//     sectionMm2: 520,
//     unitWeightGrPerM: 1050,
//     displayName: 'Sürme Rayı 40 mm',
//     tempCode: 'GC-345',
//     profileCode: 'T-2510',
//     manufacturerCode: 'Ü-90123',
//   },
//   {
//     id: '4',
//     code: 'T2514',
//     name: 'Kilit Profili',
//     variant: 'Kilit',
//     unitWeightKg: 0.97,
//     category: 'Profil',
//     subCategory: 'Kilit',
//     date: '2025-08-01',
//     image: 'https://placehold.co/600x400?text=T2514',
//     drawer: 'Serkan B.',
//     control: 'Fatma Ç.',
//     scale: '1 / 2',
//     outerSizeMm: 100,
//     sectionMm2: 380,
//     unitWeightGrPerM: 970,
//     displayName: 'Kilit Profili Standart',
//     tempCode: 'GC-456',
//     profileCode: 'T-2514',
//     manufacturerCode: 'Ü-98765',
//   },
//   {
//     id: '5',
//     code: 'T1513',
//     name: 'Fitil Kanalı',
//     variant: 'Fitil',
//     unitWeightKg: 0.35,
//     category: 'Aksesuar',
//     subCategory: 'Fitil',
//     date: '2025-08-18',
//     image: 'https://placehold.co/600x400?text=T1513',
//     drawer: 'Merve Ö.',
//     control: 'Barış T.',
//     scale: '3 / 2',
//     outerSizeMm: 60,
//     sectionMm2: 120,
//     unitWeightGrPerM: 350,
//     displayName: 'Fitil Kanalı 15 mm',
//     tempCode: 'GC-567',
//     profileCode: 'T-1513',
//     manufacturerCode: 'Ü-77889',
//   },
//   {
//     id: '6',
//     code: 'P9901',
//     name: 'Çift Açılım Set',
//     variant: 'Kanat',
//     unitWeightKg: 0.55,
//     category: 'Pencere',
//     subCategory: 'Çift Açılım',
//     date: '2025-08-20',
//     image: 'https://placehold.co/600x400?text=P9901',
//     drawer: 'Hande U.',
//     control: 'Okan Y.',
//     scale: '1 / 1',
//     outerSizeMm: 75,
//     sectionMm2: 200,
//     unitWeightGrPerM: 550,
//     displayName: 'Çift Açılım Pencere Seti',
//     tempCode: 'GC-678',
//     profileCode: 'P-9901',
//     manufacturerCode: 'Ü-65432',
//   },
// ];
